#!/bin/bash

script="~/.i3/scripts/exit.sh"

exit() {
	local action=$(yad --width 300 --center --on-top --no-taskbar --entry --title "Exit" \
		--image=gnome-shutdown \
		--button="gtk-ok:0" --button="gtk-close:1" \
		--entry-text \
		"Logout" "Shutdown" "Reboot")

	case $action in
		"Logout") i3-msg exit;;
		"Shutdown") sudo "$script" shutdown;;
		"Reboot") sudo "$script" reboot;;
	esac
}

case $BLOCK_BUTTON in
	1) exit;;
esac

# Surrounded by spaces to render a button-style like
echo "  "
echo "  "
echo
