#!/bin/bash

case $BLOCK_BUTTON in
	3) pavucontrol;;
	2) amixer -D pulse sset Master 1+ toggle;;
    4) amixer -D pulse sset Master 5%+;;
    5) amixer -D pulse sset Master 5%-;;
esac


# Use `let` to get an integer
let vol=$(amixer get Master | egrep -o "[0-9]+%" | head -1 | tr -d '%')
mute=$(amixer get Master | egrep -o "\[off\]" | head -1 | tr -d '[]')


if [ "$vol" -eq 0 ] || [ "$mute" == "off" ]; then
	text=" $vol%"
	background="#e74c3c"
	border="#d3dae3"
elif [ $vol -le 45 ]; then
	text=" $vol%"
	background=""
	border=""
else
	text=" $vol%"
	background=""
	border=""
fi

# Output in json
cat <<EOF
{
	"full_text": " ${text} ",
	"color": "",
	"background": "${background}",
	"border": "${border}",
	"border_left": 0,
	"border_right": 0,
	"border_up": 0,
	"border_bottom": 2
}
EOF
